# Generated by Django 4.1.7 on 2023-03-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.SmallIntegerField(unique=True)),
                ('name', models.CharField(db_index=True, max_length=30, unique=True)),
                ('description', models.TextField(max_length=500)),
            ],
            options={
                'ordering': ('position',),
            },
        ),
    ]
