# Generated by Django 4.1.7 on 2023-03-29 13:45

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('subtitle', models.CharField(max_length=30)),
                ('fst_descriptions', models.TextField(max_length=400)),
                ('lg_image', models.ImageField(upload_to=home.models.AboutUs.get_file_name)),
                ('sm_image1', models.ImageField(upload_to=home.models.AboutUs.get_file_name)),
                ('sm_image2', models.ImageField(upload_to=home.models.AboutUs.get_file_name)),
                ('lst_descriptions', models.TextField(max_length=500)),
            ],
        ),
    ]
