# Generated by Django 4.1.7 on 2023-03-30 13:14

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=home.models.Blog.get_file_name)),
                ('title', models.CharField(max_length=20, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=30)),
                ('small_text', models.CharField(max_length=20)),
                ('date', models.DateField(blank=True)),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ('service',)},
        ),
    ]
