# Generated by Django 4.1.7 on 2023-04-04 12:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_blog_alter_portfolio_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=30, validators=[django.core.validators.RegexValidator(regex='(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$)')])),
                ('subject', models.CharField(max_length=50)),
                ('massage', models.TextField(max_length=700)),
            ],
            options={
                'ordering': ('subject',),
            },
        ),
    ]
