# Generated by Django 4.1.7 on 2023-04-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_userreservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreservation',
            name='email',
            field=models.EmailField(max_length=30),
        ),
    ]
