# Generated by Django 4.1.7 on 2023-04-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_userreservation_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userreservation',
            options={'ordering': ('subject', '-is_processed')},
        ),
        migrations.AddField(
            model_name='userreservation',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
